# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'




target 'goodInsta' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for goodInsta
  pod 'Parse'

  target 'goodInstaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'goodInstaUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
